# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Piperig < Formula
  desc "Declarative pipeline runner for shell scripts"
  homepage "https://github.com/joarhal/piperig"
  version "0.3.10"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/joarhal/piperig/releases/download/v0.3.10/piperig_0.3.10_darwin_amd64.tar.gz"
      sha256 "5d0fbc2f4dfd6d949e39e90b65d95d5131cfa33398ab1d290ab479d96051f838"

      define_method(:install) do
        bin.install "piperig"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/joarhal/piperig/releases/download/v0.3.10/piperig_0.3.10_darwin_arm64.tar.gz"
      sha256 "6c3af2f2d8f7edefeb4467294ae71aa112e09ccd8e02a48c5a59b87103728c8e"

      define_method(:install) do
        bin.install "piperig"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/joarhal/piperig/releases/download/v0.3.10/piperig_0.3.10_linux_amd64.tar.gz"
      sha256 "2635ffe051abe313a8e88fee504d0e41c5912ef5260d4d886cf77e626ce73030"
      define_method(:install) do
        bin.install "piperig"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/joarhal/piperig/releases/download/v0.3.10/piperig_0.3.10_linux_arm64.tar.gz"
      sha256 "6efbd119464567f9f14f4a621477ab77ee720dd287935031eddbdd8cf2d062b4"
      define_method(:install) do
        bin.install "piperig"
      end
    end
  end

  test do
    system "#{bin}/piperig", "version"
  end
end
