# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Piperig < Formula
  desc "Declarative pipeline runner for shell scripts"
  homepage "https://github.com/joarhal/piperig"
  version "0.3.8"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/joarhal/piperig/releases/download/v0.3.8/piperig_0.3.8_darwin_amd64.tar.gz"
      sha256 "f5c7551531169466fc73023266d3ffafc4ec15cc6b6b0f0b918410d1367a5d9c"

      define_method(:install) do
        bin.install "piperig"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/joarhal/piperig/releases/download/v0.3.8/piperig_0.3.8_darwin_arm64.tar.gz"
      sha256 "65c0f54ea311d284c8ce46a1822d1394190349fc61d6da80a9bd9bc704d68681"

      define_method(:install) do
        bin.install "piperig"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/joarhal/piperig/releases/download/v0.3.8/piperig_0.3.8_linux_amd64.tar.gz"
      sha256 "71d30655305e7fa2fc306697576508c5356b7f055ab1585f8757d64479f4d4c6"
      define_method(:install) do
        bin.install "piperig"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/joarhal/piperig/releases/download/v0.3.8/piperig_0.3.8_linux_arm64.tar.gz"
      sha256 "d02d560bdabd7a60db69c6839678b7254c2eb9d027f83905c28968bafe6f5304"
      define_method(:install) do
        bin.install "piperig"
      end
    end
  end

  test do
    system "#{bin}/piperig", "version"
  end
end
